# Generated by Django 5.0.2 on 2024-07-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='seller',
        ),
    ]
