# Generated by Django 5.0.2 on 2024-07-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='stripe_payment_intense',
            new_name='stripe_payment_intent',
        ),
    ]
